/* ROAD_PATCH_V2: diagonal connectivity + color fix */
/*
  FILE PURPOSE:
  Central place for application constants, defaults and UI-adjustable setting limits.
*/

window.Game = window.Game || {};

window.Game.Config = {
  DEFAULT_SEED: "ISOMETRIC_MAP_28032026",
  DEFAULT_COLS: 80,
  DEFAULT_ROWS: 80,

  MIN_MAP_SIZE: 12,
  MAX_MAP_SIZE: 80,

  TILE_WIDTH: 96,
  TILE_HEIGHT: 44,

  DEFAULT_CAMERA_PITCH: 45,
  MIN_CAMERA_PITCH: 20,
  MAX_CAMERA_PITCH: 90,

  DEFAULT_DEPTH_STRENGTH: 1.0,
  MIN_DEPTH_STRENGTH: 0.6,
  MAX_DEPTH_STRENGTH: 1.8,

  DEFAULT_BLEND_PIXEL_SIZE: 4,
  MIN_BLEND_PIXEL_SIZE: 1,
  MAX_BLEND_PIXEL_SIZE: 32,

  DEFAULT_BLEND_STRENGTH: 0.2,
  MIN_BLEND_STRENGTH: 0.0,
  MAX_BLEND_STRENGTH: 0.5,

  DEFAULT_NOISE_GRID_DIVISIONS: 10,
  MIN_NOISE_GRID_DIVISIONS: 1,
  MAX_NOISE_GRID_DIVISIONS: 40,

  DEFAULT_SHOW_GRID: false,

  DEFAULT_RELIEF_ENABLED: true,

  DEFAULT_SUN_AZIMUTH: 45,
  MIN_SUN_AZIMUTH: 0,
  MAX_SUN_AZIMUTH: 359,

  DEFAULT_SUN_ELEVATION: 38,
  MIN_SUN_ELEVATION: 5,
  MAX_SUN_ELEVATION: 85,

  DEFAULT_SHADOW_STRENGTH: 0.34,
  MIN_SHADOW_STRENGTH: 0.0,
  MAX_SHADOW_STRENGTH: 1.0,

  DEFAULT_HIGHLIGHT_STRENGTH: 0.22,
  MIN_HIGHLIGHT_STRENGTH: 0.0,
  MAX_HIGHLIGHT_STRENGTH: 1.0,

  DEFAULT_SHADOW_LENGTH: 1,
  MIN_SHADOW_LENGTH: 1.0,
  MAX_SHADOW_LENGTH: 12.0,

  DEFAULT_START_ZOOM: 5.00,
  MIN_START_ZOOM: 2.0,
  MAX_START_ZOOM: 5.0,
  DEFAULT_ZOOM_STEP: 0.1,

  CAMERA_MOVE_SPEED: 18
};
