/*
  FILE PURPOSE:
  Central place for application constants and limits.
*/

window.Game = window.Game || {};

window.Game.Config = {
  DEFAULT_SEED: "ISOMETRIK_HARITA_24032026",
  DEFAULT_COLS: 80,
  DEFAULT_ROWS: 80,

  MIN_MAP_SIZE: 12,
  MAX_MAP_SIZE: 80,

  TILE_WIDTH: 96,
  TILE_HEIGHT: 44,

  DEFAULT_CAMERA_PITCH: 38,
  DEFAULT_DEPTH_STRENGTH: 1.0,
  DEFAULT_START_ZOOM: 0.8,
  MIN_CAMERA_PITCH: 20,
  MAX_CAMERA_PITCH: 65,
  MIN_DEPTH_STRENGTH: 0.6,
  MAX_DEPTH_STRENGTH: 1.8,

  CAMERA_MOVE_SPEED: 18
};
